name: ascendas
favicon: null
layout_spectrum: 0.5807319707237184
typography_spectrum: 0.4620928866788745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49659376475028694
  lightness: 0.5011495181825012
  saturation: 0.7703175011556596
  rhythmicContrast: 0.8172270313370973
purpose: []
