name: ascendas
favicon: null
layout_spectrum: 0.21898802742362022
typography_spectrum: 0.3289072217885405
title: ascendas test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.1849149742629379
  lightness: 0.9457824758719653
  saturation: 0.28871238115243614
  rhythmicContrast: 0.7294063286390156
purpose: []
